# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://chendx79.github.io
date_format: "ordinal"
title: 陈鼎星的个人博客 
subtitle: ""
description: "陈鼎星的个人博客"
keywords: 陈鼎星, chendx79
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: DingXing Chen
organization: Wanda
organization_url: http://www.wanda.cn
github_username: chendx79
location: Shanghai, China
email: chendx79@hotmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chendx79/chendx79.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: chendx79 
    repo: blog-comments
    oauth:
        client_id: 3a027ed87231221278a8 
        client_secret: bef57c5a0996bd2a3ecb16a34e79706a9ee90d84 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: chendx79 
    repo: blog-comments
    clientID: 3a027ed87231221278a8 
    clientSecret: bef57c5a0996bd2a3ecb16a34e79706a9ee90d84 
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
